blank_issues_enabled: true
contact_links:
  - name: 💬 Discussão geral
    url: https://github.com/LucasGCarboni/Pipeline-CI-CD-Bolsa-de-Valores
    about: Use este espaço para perguntas, ideias ou sugestões abertas que não se encaixem em issues.
